import re

str="hhlw i am prateek jain. and my age is 21"

a=re.findall('\S',str)
print('findall method : ',a)
print()
print('find alpha : ',re.findall('[A-Za-z]',str))
print()
print('find begin h : ',re.findall('[\bh]',str))
print()
print('find all except digits : ',re.findall('[^0-9]',str))
print()
print('find word starting with p and end with k : ',re.findall('p.....k',str))
print()
print('find digit : ',re.findall('[0-9]',str))
print()
b=re.split('\s',str)
print('split method : ',b)
print()
print('search method : ',re.search('\s',str))
print()
print('position : ',re.search('a|w',str))
print()
print('sub method : ',re.sub('\w','2',str)) 
print()
print('bitwise operator or : ')
x=re.findall('p|w',str)
if (x):
    print('true')
print()
print('bitwise operator and : ')
y=re.findall('p&z',str)
if (y):
    print('true')
else:
    print('false')
print()
print('digit finding : ',re.findall('\d',str)) 
print()
print('alpha finding : ',re.findall('\D',str)) 
print()
print('space finding : ',re.findall('\s',str)) 
print()
print('except space finding : ',re.findall('\S',str)) 
print()
print('except words finding : ',re.findall('\W',str)) 
print()
print('search method : ',re.search(r'\ba\w+',str)) 
print()
print('digit finding : ',re.findall('[^a-z]',str)) 
print()
print('digit finding : ',re.findall('\w*',str)) 
print()

