import re

line='prat5eek is@ a g7oo%d boy'
print('a-f : ',re.split('[a-f]',line))
print()
print('\w : ',re.split('\w',line))
print()
print('\W : ',re.split('\W',line))
print()
print('\s : ',re.split('\s',line))
print()
print('\S : ',re.split('\S',line))
print()
print('0-2 :',re.split('[0-2]',line))
print()
print('0-9,a-f : ',re.split('[a-f,0-9]',line))
print()
print(r'\ba : ',re.split(r'\ba',line))
print()
print('\D : ',re.split('\D',line))
print()
print('\d : ',re.split('\d',line))
print()
print('\B : ',re.split('\B',line))
print()
print('^p : ',re.split('^p',line))
print()
print('x*: ',re.split('x*',line))
print()

